// Define the request for user creation 
POST http://localhost:4000/api/user/create
Content-Type: application/json

{
    "name" : "imane",
    "email": "imane@email.com",
    "password":"azeertyy"
}

######
POST http://localhost:4000/api/user/verify-email
Content-Type: application/json

{
    "userId" : "679588ae3af6001162e78e0f",
    "OTP" : "514383"

}
######

POST http://localhost:4000/api/user/sign-in
Content-Type: application/json

{
    "email": "imane@email.com",
    "password":"azeertyy"
}

######
POST http://localhost:4000/api/user/resend-email-verification-token
Content-Type: application/json

{
    "userId" : "6795a016e3d4496119c7170c"
}

######

POST http://localhost:4000/api/user/forget-password
Content-Type: application/json

{
    "email" : "imane@email.com"

}

######


